/** IPC channel names only — safe for preload bundle without pulling zod. */
export const IPC_CHANNELS = {
  START_SCAN: "scan:start",
  RESET_SCAN_DATA: "scan:reset",
  START_BULK_DUPLICATE_REFRESH: "duplicates:refreshJob",
  CANCEL_JOB: "jobs:cancel",
  PICK_PATHS: "dialog:pickPaths",
  GET_DASHBOARD: "dashboard:get",
  GET_DUPLICATES: "duplicates:get",
  APPLY_DECISION: "duplicates:decision",
  DELETE_DUPLICATE_CANDIDATE: "duplicates:deleteCandidate",
  SKIP_DUPLICATE_GROUP: "duplicates:skipGroup",
  SHOW_ITEM_IN_FOLDER: "shell:showItemInFolder",
  DIALOG_CONFIRM: "dialog:confirm",
  GET_QUARANTINE: "quarantine:get",
  RESTORE_QUARANTINE: "quarantine:restore",
  DELETE_QUARANTINE: "quarantine:deletePermanently",
  GET_SETTINGS: "settings:get",
  SET_SETTINGS: "settings:set",
  GET_HISTORY: "history:get",
  GET_APP_PATHS: "app:paths",
  ON_PROGRESS: "jobs:progress",
  DETECT_IPODS: "devices:detect",
  GET_IPOD_LIBRARY: "devices:library",
  QUERY_IPOD_LIBRARY_TRACKS: "devices:libraryTracks",
  BROWSE_IPOD: "devices:browse",
  EXPORT_IPOD_TRACKS: "devices:exportTracks",
  COPY_TO_IPOD: "devices:copyToDevice",
  DELETE_FROM_IPOD: "devices:deleteFromDevice"
} as const;
